version: '3'
services:
  advent-calendar:
    build:
      context: .  # Dockerfile이 위치한 현재 디렉토리
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_MODE: "dev"  # 환경 변수로 서버 모드 지정
    volumes:
      - "/c/pinpoint-agent-3.0.1:/pinpoint"
    container_name: advent-calendar-app
    depends_on:
      - mysql  # MySQL 서비스가 먼저 시작되도록 설정
  mysql:
    image: mysql:8.0  # MySQL 버전 지정
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "test"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터 유지

volumes:
  mysql_data: