#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/test
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: demo
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        ddl-auto: none
#server:
#  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name: demo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

